/**
 * 本文件实现本机图库作品详情、全宽任务记录列表和本地任务详情弹窗。
 */
import type { DesktopLocalJobView, DesktopLocalLoraView, DesktopWebsiteLoraView } from "@drawhime/contracts";
import { ArrowLeft, CalendarClock, Copy, Image, Layers3, LoaderCircle, Maximize2, Settings2, X } from "lucide-react";
import { convertFileSrc } from "@tauri-apps/api/core";
import { useEffect, useState } from "react";

interface GalleryDataProps {
  jobs: DesktopLocalJobView[];
  loras: DesktopLocalLoraView[];
  websiteLoras: DesktopWebsiteLoraView[];
}

/** 图库列表只展示真实本地产物，点击封面进入包含完整参数与 LoRA 的作品详情页。 */
export function LocalGalleryPage({ jobs, loras, websiteLoras }: GalleryDataProps) {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const galleryJobs = jobs.filter((job) => Boolean(job.artifact));
  const selected = galleryJobs.find((job) => job.id === selectedId) || null;
  if (selected) return <GalleryDetail job={selected} loras={loras} websiteLoras={websiteLoras} onBack={() => setSelectedId(null)} />;
  return <div className="desktop-page gallery-page"><section className="section-card"><header><div><span>LOCAL GALLERY</span><h2>本机图库</h2></div><small>{galleryJobs.length} 张</small></header><div className="gallery-grid">{galleryJobs.map((job) => <button key={job.id} className="gallery-card" onClick={() => setSelectedId(job.id)}><div className="gallery-cover"><img loading="lazy" src={convertFileSrc(job.artifact!.path)} alt={job.prompt.slice(0, 80)} /><i>{job.privacy === "private" ? "私有" : "公开"}</i><em><Maximize2 />查看作品</em></div><div className="gallery-copy"><strong>{job.prompt}</strong><span>{job.modelDisplayName} · {job.parameters.width}×{job.parameters.height} · {job.loras.length} 个 LoRA</span></div></button>)}</div>{galleryJobs.length === 0 && <div className="empty-block">当前还没有本机生成图片</div>}</section></div>;
}

/** 记录页按全宽长条展示任务，点击任意记录打开与网页端语义一致的详情弹窗。 */
export function LocalJobsPage({ jobs, loras, websiteLoras, onCancel }: GalleryDataProps & { onCancel: (id: string) => void }) {
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const selected = jobs.find((job) => job.id === selectedId) || null;
  return <div className="desktop-page local-record-page"><section className="section-card"><header><div><span>LOCAL JOBS</span><h2>任务记录</h2></div><small>{jobs.length} 项</small></header>{jobs.length ? <div className="local-record-list">{jobs.map((job) => <article key={job.id} className={`is-${job.status}`} onClick={() => setSelectedId(job.id)}><div className="local-record-preview">{job.artifact ? <img loading="lazy" src={convertFileSrc(job.artifact.path)} alt={job.prompt.slice(0, 80)} /> : <div><Image /><span>{job.progress}%</span></div>}</div><div className="local-record-copy"><div><b className={`job-status is-${job.status}`}>{jobStatusLabel(job.status)}</b><span>{shortId(job.id)}</span></div><strong>{job.prompt}</strong><small>{job.modelDisplayName} · {job.parameters.width}×{job.parameters.height} · {job.loras.length} 个 LoRA · Seed {job.parameters.seed}</small>{job.error && <em>{job.error}</em>}</div><div className="local-record-time"><span>{formatTime(job.createdAt)}</span><small>{job.completedAt ? durationLabel(job) : job.status === "running" ? `生成进度 ${job.progress}%` : job.status === "queued" ? "等待本地 Runtime" : "任务未完成"}</small></div><button className="local-record-detail" onClick={(event) => { event.stopPropagation(); setSelectedId(job.id); }}>详情</button>{["queued", "running"].includes(job.status) && <button className="local-record-cancel" title="取消任务" onClick={(event) => { event.stopPropagation(); onCancel(job.id); }}><X /></button>}</article>)}</div> : <div className="empty-block">尚未提交本地生成任务</div>}</section>{selected && <LocalJobDetailDialog job={selected} loras={loras} websiteLoras={websiteLoras} onClose={() => setSelectedId(null)} onCancel={onCancel} />}</div>;
}

function GalleryDetail({ job, loras, websiteLoras, onBack }: { job: DesktopLocalJobView; loras: DesktopLocalLoraView[]; websiteLoras: DesktopWebsiteLoraView[]; onBack: () => void }) {
  return <div className="desktop-page gallery-detail"><button className="gallery-detail-back" onClick={onBack}><ArrowLeft />返回本机图库</button><section className="gallery-detail-hero"><div className="gallery-detail-image"><img src={convertFileSrc(job.artifact!.path)} alt={job.prompt.slice(0, 120)} /></div><div className="gallery-detail-summary"><div className="gallery-detail-tags"><i>{job.privacy === "private" ? "私有" : "公开"}</i><i>{job.artifact!.width}×{job.artifact!.height}</i></div><h1>{job.prompt}</h1><p>{job.modelDisplayName} · {job.loras.length} 个 LoRA</p><dl><InfoLine label="任务 ID" value={job.id} copy /><InfoLine label="生成时间" value={formatTime(job.completedAt || job.createdAt)} /><InfoLine label="文件大小" value={formatBytes(job.artifact!.byteSize)} /><InfoLine label="文件 SHA-256" value={job.artifact!.sha256} copy /></dl></div></section><PromptCards job={job} /><section className="gallery-detail-section"><header><Layers3 /><div><span>USED LORAS</span><h2>使用的 LoRA</h2></div><small>{job.loras.length} 个</small></header>{job.loras.length ? <div className="job-lora-gallery">{job.loras.map((lora) => <JobLoraCard key={lora.id} lora={lora} localLoras={loras} websiteLoras={websiteLoras} />)}</div> : <div className="empty-block compact">该作品未使用 LoRA</div>}</section><ParameterPanel job={job} /></div>;
}

function LocalJobDetailDialog({ job, loras, websiteLoras, onClose, onCancel }: { job: DesktopLocalJobView; loras: DesktopLocalLoraView[]; websiteLoras: DesktopWebsiteLoraView[]; onClose: () => void; onCancel: (id: string) => void }) {
  useEffect(() => {
    const closeOnEscape = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); };
    window.addEventListener("keydown", closeOnEscape);
    return () => window.removeEventListener("keydown", closeOnEscape);
  }, [onClose]);
  return <div className="job-detail-backdrop" role="presentation" onMouseDown={(event) => { if (event.currentTarget === event.target) onClose(); }}><section className="job-detail-dialog" role="dialog" aria-modal="true" aria-label="本地任务详情"><header><div><b className={`job-status is-${job.status}`}>{jobStatusLabel(job.status)}</b><span>任务详情 · {shortId(job.id)}</span></div><button onClick={onClose} aria-label="关闭任务详情"><X /></button></header><div className="job-detail-body"><section className="job-detail-overview"><div className="job-detail-preview">{job.artifact ? <img src={convertFileSrc(job.artifact.path)} alt={job.prompt.slice(0, 80)} /> : <div>{job.status === "running" ? <LoaderCircle className="spin" /> : <Image />}<strong>{job.progress}%</strong><span>{jobStatusLabel(job.status)}</span></div>}</div><div><h2>{job.prompt}</h2><p>{job.modelDisplayName}</p><dl><InfoLine label="创建" value={formatTime(job.createdAt)} /><InfoLine label="开始" value={job.startedAt ? formatTime(job.startedAt) : "-"} /><InfoLine label="完成" value={job.completedAt ? formatTime(job.completedAt) : "-"} /><InfoLine label="Runtime Prompt" value={job.runtimePromptId || "-"} copy={Boolean(job.runtimePromptId)} /></dl></div></section><PromptCards job={job} /><ParameterPanel job={job} /><section className="job-detail-section"><header><Layers3 /><strong>LoRA 快照</strong><small>{job.loras.length} 个</small></header>{job.loras.length ? <div className="job-lora-gallery">{job.loras.map((lora) => <JobLoraCard key={lora.id} lora={lora} localLoras={loras} websiteLoras={websiteLoras} />)}</div> : <div className="empty-block compact">未使用 LoRA</div>}</section><section className="job-detail-section"><header><CalendarClock /><strong>执行尝试</strong><small>{job.attempts.length} 次</small></header><div className="job-attempt-list">{job.attempts.length ? job.attempts.map((attempt) => <article key={attempt.id}><i className={`is-${attempt.status}`} /><div><strong>第 {attempt.attemptNumber} 次 · {attemptStatusLabel(attempt.status)}</strong><span>{formatTime(attempt.startedAt)}{attempt.completedAt ? ` → ${formatTime(attempt.completedAt)}` : ""}</span>{attempt.error && <small>{attempt.error}</small>}</div></article>) : <div className="empty-block compact">尚未创建 Runtime 尝试</div>}</div></section>{job.error && <div className="job-detail-error"><X /><span>{job.error}</span></div>}</div><footer><button onClick={onClose}>关闭</button>{["queued", "running"].includes(job.status) && <button className="danger" onClick={() => { onCancel(job.id); onClose(); }}>取消任务</button>}</footer></section></div>;
}

function PromptCards({ job }: { job: DesktopLocalJobView }) { return <section className="job-prompt-grid"><article><header><Copy /><strong>提示词</strong><button onClick={() => void navigator.clipboard.writeText(job.prompt)}>复制</button></header><p>{job.prompt}</p></article>{job.negativePrompt && <article className="negative"><header><Copy /><strong>负面提示词</strong><button onClick={() => void navigator.clipboard.writeText(job.negativePrompt || "")}>复制</button></header><p>{job.negativePrompt}</p></article>}</section>; }
function ParameterPanel({ job }: { job: DesktopLocalJobView }) { const parameters = job.parameters; return <section className="job-parameter-panel"><header><Settings2 /><div><span>GENERATION PARAMETERS</span><h2>生成参数</h2></div></header><div><Parameter label="底模" value={job.modelDisplayName} /><Parameter label="质量档" value={presetLabel(parameters.qualityPreset)} /><Parameter label="输出尺寸" value={`${parameters.width} × ${parameters.height}`} /><Parameter label="采样预算" value={`${parameters.samplingPixelBudget.toLocaleString()} px`} /><Parameter label="采样最长边" value={String(parameters.samplingMaxEdge)} /><Parameter label="步数" value={`${parameters.steps} / 极端 ${parameters.aspectAdjustedSteps}`} /><Parameter label="画幅阈值" value={String(parameters.aspectStepThreshold)} /><Parameter label="CFG" value={String(parameters.cfg)} /><Parameter label="采样器" value={parameters.samplerName} /><Parameter label="调度器" value={parameters.schedulerName} /><Parameter label="输出缩放" value={parameters.upscaleMethod} /><Parameter label="质量前缀" value={parameters.qualityPromptEnabled ? parameters.qualityPrefix || "开启" : "关闭"} /><Parameter label="默认负面词" value={parameters.defaultNegativeEnabled ? parameters.defaultNegativePrompt || "开启" : "关闭"} /><Parameter label="Seed" value={String(parameters.seed)} /><Parameter label="模型 SHA" value={job.modelSha256.slice(0, 16)} /></div></section>; }
function JobLoraCard({ lora, localLoras, websiteLoras }: { lora: DesktopLocalJobView["loras"][number]; localLoras: DesktopLocalLoraView[]; websiteLoras: DesktopWebsiteLoraView[] }) { const local = localLoras.find((item) => item.id === lora.id || item.sha256 === lora.sha256); const website = websiteLoras.find((item) => item.sha256 === lora.sha256); return <article className="job-lora-card"><div className="job-lora-cover">{website?.coverPath ? <img src={convertFileSrc(website.coverPath)} alt={lora.title} /> : <Layers3 />}</div><div><span>{loraTypeLabel(lora.type)}</span><strong>{local?.title || website?.title || lora.title}</strong><small>{lora.fileName}</small></div><b title="模型强度 / CLIP 强度">{lora.strength.toFixed(2)} / {lora.clipStrength.toFixed(2)}</b></article>; }
function InfoLine({ label, value, copy = false }: { label: string; value: string; copy?: boolean }) { return <div><dt>{label}</dt><dd title={value}>{value}{copy && <button onClick={() => void navigator.clipboard.writeText(value)}><Copy /></button>}</dd></div>; }
function Parameter({ label, value }: { label: string; value: string }) { return <article><span>{label}</span><strong title={value}>{value}</strong></article>; }
function jobStatusLabel(status: DesktopLocalJobView["status"]): string { return { queued: "排队中", running: "生成中", succeeded: "已完成", failed: "失败", cancelled: "已取消" }[status]; }
function attemptStatusLabel(status: DesktopLocalJobView["attempts"][number]["status"]): string { return { running: "执行中", succeeded: "成功", failed: "失败", cancelled: "已取消", interrupted: "已中断" }[status]; }
function loraTypeLabel(type: string): string { return { style: "画风", character: "角色", concept: "概念", clothing: "服装", pose: "姿势", other: "其他" }[type] || type; }
function presetLabel(preset: DesktopLocalJobView["parameters"]["qualityPreset"]): string { return { fast: "快速", quality: "质量", extreme: "极致", custom: "自定义" }[preset]; }
function shortId(value: string): string { return value.slice(0, 8); }
function formatTime(value: string): string { return new Date(value).toLocaleString("zh-CN", { hour12: false }); }
function formatBytes(value: number): string { return value < 1024 ** 2 ? `${Math.max(1, Math.round(value / 1024))} KiB` : value < 1024 ** 3 ? `${(value / 1024 ** 2).toFixed(1)} MiB` : `${(value / 1024 ** 3).toFixed(2)} GiB`; }
function durationLabel(job: DesktopLocalJobView): string { if (!job.startedAt || !job.completedAt) return "已完成"; const seconds = Math.max(0, Math.round((new Date(job.completedAt).getTime() - new Date(job.startedAt).getTime()) / 1000)); return seconds < 60 ? `${seconds} 秒` : `${Math.floor(seconds / 60)} 分 ${seconds % 60} 秒`; }
