/** 本文件保存独立本地模型平台 backend 使用的第一批真实模型注册数据。 */

/** 本地模型注册条目。 */
export type LocalModelRegistrySeed = {
  /** 注册键。 */
  modelKey: string;
  /** 展示名。 */
  displayName: string;
  /** 用途分类。 */
  usage: 'generation' | 'training' | 'caption' | 'vae' | 'utility';
  /** 来源。 */
  source: 'builtin' | 'user_uploaded' | 'external_registry';
  /** 精度。 */
  precision: 'bf16' | 'fp16' | 'fp8' | 'nvfp4' | 'int8' | 'int4' | 'unknown';
  /** 默认宽度。 */
  defaultWidth: number;
  /** 默认高度。 */
  defaultHeight: number;
  /** 默认步数。 */
  defaultSteps: number;
  /** 默认 CFG。 */
  defaultCfg: number | null;
  /** 推荐显存。 */
  vramRecommendedGb: number | null;
  /** 标签。 */
  tags: string[];
  /** 备注。 */
  notes: string;
  /** 目标相对目录。 */
  relativeDir: string;
};

/** 第一批支持的模型清单。 */
export const LOCAL_MODEL_REGISTRY_SEED: readonly LocalModelRegistrySeed[] = [
  {
    modelKey: 'krea2_raw_bf16.safetensors',
    displayName: 'Krea 2 Raw',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 30,
    defaultCfg: 4.5,
    vramRecommendedGb: 24,
    tags: ['基础模型', '原生风格', '高保真'],
    notes: '适合作为原始生成底座，保留更完整的图像表达空间。',
    relativeDir: 'models/diffusion_models',
  },
  {
    modelKey: 'krea2_turbo_bf16.safetensors',
    displayName: 'Krea 2 Turbo BF16',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 24,
    defaultCfg: 4,
    vramRecommendedGb: 24,
    tags: ['快速生成', '高质量', '通用'],
    notes: '适合日常快速出图和稳定预览。',
    relativeDir: 'models/diffusion_models',
  },
  {
    modelKey: 'krea2_turbo_fp8_scaled.safetensors',
    displayName: 'Krea 2 Turbo FP8',
    usage: 'generation',
    source: 'builtin',
    precision: 'fp8',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 24,
    defaultCfg: 4,
    vramRecommendedGb: 16,
    tags: ['轻量推理', '快速生成', '节省显存'],
    notes: '适合显存较紧张但仍希望维持较好输出质量的场景。',
    relativeDir: 'models/diffusion_models',
  },
  {
    modelKey: 'krea2_turbo_nvfp4.safetensors',
    displayName: 'Krea 2 Turbo NVFP4',
    usage: 'generation',
    source: 'external_registry',
    precision: 'nvfp4',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 22,
    defaultCfg: 4,
    vramRecommendedGb: 12,
    tags: ['超轻量', '快速生成', '低显存'],
    notes: '用于更轻量的推理部署，具体效果依赖当前运行后端支持。',
    relativeDir: 'models/diffusion_models',
  },
  {
    modelKey: 'krea2_darkbrush.safetensors',
    displayName: 'Krea 2 Dark Brush LoRA',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 20,
    defaultCfg: 4,
    vramRecommendedGb: 12,
    tags: ['LoRA', '暗色笔触', '风格化'],
    notes: '暗色画笔风格 LoRA，适合作风格叠加。',
    relativeDir: 'models/loras',
  },
  {
    modelKey: 'krea2_dotmatrix.safetensors',
    displayName: 'Krea 2 Dot Matrix LoRA',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 20,
    defaultCfg: 4,
    vramRecommendedGb: 12,
    tags: ['LoRA', '点阵', '风格化'],
    notes: '点阵化视觉风格 LoRA。',
    relativeDir: 'models/loras',
  },
  {
    modelKey: 'krea2_kidsdrawing.safetensors',
    displayName: 'Krea 2 Kids Drawing LoRA',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 20,
    defaultCfg: 4,
    vramRecommendedGb: 12,
    tags: ['LoRA', '儿童涂鸦', '轻松'],
    notes: '儿童画、涂鸦感风格 LoRA。',
    relativeDir: 'models/loras',
  },
  {
    modelKey: 'krea2_neondrip.safetensors',
    displayName: 'Krea 2 Neon Drip LoRA',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 20,
    defaultCfg: 4,
    vramRecommendedGb: 12,
    tags: ['LoRA', '霓虹', '潮流'],
    notes: '霓虹滴落感风格 LoRA。',
    relativeDir: 'models/loras',
  },
  {
    modelKey: 'krea2_rainywindow.safetensors',
    displayName: 'Krea 2 Rainy Window LoRA',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 20,
    defaultCfg: 4,
    vramRecommendedGb: 12,
    tags: ['LoRA', '雨窗', '氛围'],
    notes: '雨窗氛围风格 LoRA。',
    relativeDir: 'models/loras',
  },
  {
    modelKey: 'krea2_retroanime.safetensors',
    displayName: 'Krea 2 Retro Anime LoRA',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 20,
    defaultCfg: 4,
    vramRecommendedGb: 12,
    tags: ['LoRA', '复古动画', '二次元'],
    notes: '复古动画风格 LoRA。',
    relativeDir: 'models/loras',
  },
  {
    modelKey: 'krea2_softwatercolor.safetensors',
    displayName: 'Krea 2 Soft Watercolor LoRA',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 20,
    defaultCfg: 4,
    vramRecommendedGb: 12,
    tags: ['LoRA', '水彩', '柔和'],
    notes: '柔和水彩风格 LoRA。',
    relativeDir: 'models/loras',
  },
  {
    modelKey: 'krea2_sunsetblur.safetensors',
    displayName: 'Krea 2 Sunset Blur LoRA',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 20,
    defaultCfg: 4,
    vramRecommendedGb: 12,
    tags: ['LoRA', '黄昏', '虚化'],
    notes: '黄昏模糊氛围风格 LoRA。',
    relativeDir: 'models/loras',
  },
  {
    modelKey: 'krea2_turbo_lora_rank_64_bf16.safetensors',
    displayName: 'Krea 2 Turbo LoRA Rank 64',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 20,
    defaultCfg: 4,
    vramRecommendedGb: 16,
    tags: ['LoRA', '通用', '高兼容'],
    notes: '通用 Turbo LoRA 底座，适合后续继续微调。',
    relativeDir: 'models/loras',
  },
  {
    modelKey: 'krea2_vintagetarot.safetensors',
    displayName: 'Krea 2 Vintage Tarot LoRA',
    usage: 'generation',
    source: 'builtin',
    precision: 'bf16',
    defaultWidth: 1536,
    defaultHeight: 1024,
    defaultSteps: 20,
    defaultCfg: 4,
    vramRecommendedGb: 12,
    tags: ['LoRA', '复古塔罗', '神秘'],
    notes: '复古塔罗与神秘感风格 LoRA。',
    relativeDir: 'models/loras',
  },
  {
    modelKey: 'qwen3vl_4b_fp8_scaled.safetensors',
    displayName: 'Qwen3-VL 4B FP8',
    usage: 'caption',
    source: 'builtin',
    precision: 'fp8',
    defaultWidth: 1024,
    defaultHeight: 1024,
    defaultSteps: 1,
    defaultCfg: null,
    vramRecommendedGb: 12,
    tags: ['识图', '标签', '标题生成'],
    notes: '用于图片理解、标签生成、标题生成和提示词整理。',
    relativeDir: 'models/text_encoders',
  },
  {
    modelKey: 'qwen_image_vae.safetensors',
    displayName: 'Qwen Image VAE',
    usage: 'vae',
    source: 'builtin',
    precision: 'fp16',
    defaultWidth: 1024,
    defaultHeight: 1024,
    defaultSteps: 1,
    defaultCfg: null,
    vramRecommendedGb: 4,
    tags: ['VAE', '解码', '图像编解码'],
    notes: '用于图像潜空间编解码，属于基础资产，不参与直接出图。',
    relativeDir: 'models/vae',
  },
];
